config/routes.rb
Rails.application.routes.draw do
  get 'employees/index'
  root "home#index"
  # custome routes define karne ke way.
 # get 'home/index'
 #get '/home' => 'home#index'
 
 resources :employees
 resources :documents

 #public/Custom pages Routes 
 get 'about'  => 'pages#about_us'
 get 'contact' => "pages#contact_us"
 get 'privacy_policy' => 'pages#privacy_policy'
 get 'terms_and_conditions' => 'pages#terms_and_conditions'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
# Constant always declare on Top in model
 DOC_TYPES = ["Markesheet", "PanCard","AddressProof", "Photo Id", "Others"].freeze

  belongs_to :employee
  
  # active storage define esko (:image) ko document ke form kese use karna hai 
  # or  Document ke controller me kese permit karna hai "params" me
  has_one_attached :image

  validates :name, :doc_type, presence:true

end

app/models/employee.rb
class Employee < ApplicationRecord

   has_many :documents
    validates :first_name, :last_name, presence:true
    validates :email , presence:true , uniqueness:true
    validates :city, :state,:country,:pincode, :address_line_1, presence:true
    
    validates :date_of_birth, :date_of_joining, :job_title , presence:true

    #Using Instance method for  jis se hame jayada html code likhna na pade
    #Note :- Model ki instance method ka use ham , model ke index template ke ander "table-body" 
    #me use karte hai , esa karne se table ke ek hi cloumn me ye tino name ("#{first_name} #{middle_name} #{last_name}" ) 
    # ek sath karte hai 

    # name or address instance method ka use employee ke  index tamplate me kiya 
    def name
        "#{first_name} #{middle_name} #{last_name}"
    end

    def address
        "#{address_line_1}, #{city},#{pincode},#{state},#{country}"
    end

    #eska use me document ke partial form ka karene
    def name_with_email
        "#{name}(#{email})"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  #using befor_action filter 
  before_action :set_document, only:[:edit,:show,:update,:destroy]

    def index
        @documents = Document.all
    end

    def new
        @document = Document.new
    end
    
    def create 
        @document = Document.new(document_params)

        if @document.save
        redirect_to documents_path , notice:"Document has been created sucessfully"
        else
        render :new
        end
    end

    def edit 
    
    end

    def update  
    
        if @document.update(document_params)
        redirect_to documents_path , notice:"Document has been updated sucessfully"
        else
        render :edit
        end
    end

    def show 
    
    end

    def destroy
        if @document.destroy
        redirect_to documents_path , notice:"Document has been Deleted sucessfully"
        end
    end

    private
    def document_params
    params.require(:document).permit(:name,:doc_type,:employee_id,:image)
    end

    #create a filter method use in :edit , :show, :update, :destroy
    private
    def set_document
        @document = Document.find(params[:id])
        rescue  ActiveRecord::RecordNotFound => error
        redirect_to  documents_path , notice:error
    end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

   #using befor_action filter 
   before_action :set_employee, only:[:edit,:show,:update,:destroy]

  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end
 def create 
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path , notice:"Employee has been created sucessfully"
    else
      render :new
    end
 end

  def edit 
   
  end

  def update  
   
    if @employee.update(employee_params)
      redirect_to employees_path , notice:"Employee has been updated sucessfully"
    else
      render :edit
    end
  end

  def show 
   
  end

  def destroy
     if @employee.destroy
      redirect_to employees_path , notice:"Employee has been Deleted sucessfully"
    end
  end

 private
 def employee_params
  params.require(:employee).permit(:first_name , :last_name, :middle_name,:email,:city,:state,:country,:address_line_1,:pincode,
  :date_of_birth,:job_title,:date_of_joining,:about)
 end

 #create a filter method use in :edit , :show, :update, :destroy
 private
 def set_employee
  @employee = Employee.find(params[:id])
 rescue  ActiveRecord::RecordNotFound => error
  redirect_to  employees_path , notice:error
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Hello Wolrd!"
    @sub_title="I am learning Rails !!"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form|%>

<div class="row">
    <div class = "col-lg-4"> 
                <div class="from-group">
                    <%=form.label :name, class:'mb-2'%>
                    <%= form.text_field :name, class:"form-control form-control-lg rounded-0"%>
                </div>
                <% @document.errors.full_messages_for(:name).each do |msg|%>
                    <p class = "text-danger"><%= msg%> </p>
                <% end%>
    

    
            <!--    # Drop_Down for Doc_Type
                  <div class="from-group">
                    <%=form.label :doc_type, class:'mb-2'%>
                    <%= form.text_field :doc_type, class:"form-control form-control-lg rounded-0"%>
                </div> -->

                <div class="from-group">
                    <%=form.label :doc_type, class:'mb-2 mt-2'%>
                    <%= form.select :doc_type , options_for_select(Document::DOC_TYPES, selected: document.doc_type), 
                    {prompt: 'Select Document Type'}, class: "form-select form-select-lg rounded-0"%>
                </div>

                <% @document.errors.full_messages_for(:doc_type).each do |msg|%>
                    <p class = "text-danger"><%= msg%> </p>
                <% end%>
    
    
                <div class="from-group">
                    <%=form.label :employee_id, class:'mb-2 mt-2'%>
                   <%= form.select :employee_id , options_for_select(Employee.all.map{|employee| [employee.name_with_email , employee.id]}, selected: document.doc_type), 
                    {prompt: 'Select Employee Type'}, class: "form-select form-select-lg rounded-0"%>

                     <%#= form.select :employee_id , options_for_select(Employee.pluck(:name,:id), selected: document.doc_type), 
                    {prompt: 'Select Employee Type'}, class: "form-select form-select-lg rounded-0"%>


                <!--    <%= form.number_field :employee_id, class:"form-control form-control-lg rounded-0"%>  -->
                </div>
               <% @document.errors.full_messages_for(:employee_id).each do |msg|%>
                    <p class = "text-danger"><%= msg%> </p>
                <% end%>


                 <div class="from-group">
                 <%= form.label :image, class:'mb-2 mt-4'%>
                 <%=form.file_field :image%>
                 </div>
    </div>

</div>

<div class="row">
   <div class= "col-lg-4 mt-3">
     <%= form.submit class: "btn btn-primary btn-lg mb-4 rounded-0"%>
     <%= link_to "Back To Documents" , documents_path,class: "btn btn-outline-primary btn-lg mb-4 rounded-0" %>
   </div>
</div>

<%end%>

app/views/documents/edit.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-4 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Edit Document </h2>
        </div>
    </div>

     <%= render 'form', document:@document%>

</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
<%= flash[:notice]%>
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Listing Documents </h2>
        </div>
    </div>
    <%= link_to "Create New document", new_document_path, class: "btn btn-primary btn-lg mb-4 "%>
    <table class ="table table-bordered text-center">
        <thead>
            <tr>
                    <th>Name</th>
                    <th>Doc Type</th>
                    <th>document</th>
                    <th>Action</th>
            </tr>
    </thead>
        <tbody>
            <% @documents.each  do |document|%>
                <tr>
                    <td><%= document.name%></td>
                    <td><%= document.doc_type%></td>
                    <!--<td><%= document.employee.name%></td> -->
                    <td><%=link_to document.employee.name, employee_path(document.employee)%></td>
                    <td>
            <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Edit", edit_document_path(document), class: "dropdown-item "%></li>
                <li><%= link_to "View", document_path(document), class: "dropdown-item"%></li>
                <li><%= link_to "Delete", document_path(document), class: "dropdown-item", method: :delete, data: {confirm: "Are You sure delete this document?"}%></li>
            </ul>
            </div>
 <!--   Button(edit / view / delete) dene ka another way         
 <%= link_to "View", document_path(document), class: "btn btn-info btn-lg mb-4"%>

<%= link_to "Delete", document_path(document), class: "btn btn-danger btn-lg mb-4", method: :delete, data: {confirm: "Are You sure delete this document?"}%>
<%= link_to "Edit", edit_document_path(document), class: "btn btn-primary btn-lg mb-4"%>
-->
            </td>

                </tr>
            <%end%>
        </tbody>
    </table>

</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-4 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Create New Document </h2>
        </div>
    </div>

     <%= render 'form', document:@document%>

</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-4 mb-5">
    <div class="card-body">
        <h2 class="text-center">  document Details  </h2>
            <div class ="row mt-5">
                <div class="col-lg-6">
                <% if @document.image.attached?%>
                  <%= image_tag @document.image%>
                  <%end%>
                    <p class="lead"><strong>Name: </strong><%=@document.name%></p>
                    <p class="lead"><strong>doc_type: </strong><%=@document.doc_type%></p>
                    <p class="lead"><strong>Employee: </strong><%=@document.employee.name%></p>
                </div>

                
            </div>
      <%= link_to "Edit document", edit_document_path(@document), class:"btn btn-primary btn-lg"%>
     <%= link_to "Back to documents", documents_path, class:"btn btn-outline-primary btn-lg "%>

    </div>
</div>

</div>

app/views/employees/_form.html.erb
<%= form_with model: employee do |form|%>
  <div class= "row">
    <!--
        <% if @employee.errors.any?%> 
            <div class="col-lg-6">
                <p class="lead">Please fix the errors</p>
                    <% @employee.errors.full_messages.each do |message|%>
                        <p class = "text-danger"> <%=message %> </p>
                    <%end%>
            </div>
       <% end%>
     
   -->
        <div class = "col-lg-4"> 
                <div class="from-group">
                    <%=form.label :first_name, class:'mb-2'%>
                    <%= form.text_field :first_name, class:"form-control form-control-lg rounded-0"%>
                </div>
                <% @employee.errors.full_messages_for(:first_name).each do |msg|%>
                    <p class = "text-danger"><%= msg%> </p>
                <% end%>
        </div>
       
       <div class= "col-lg-4">
                <div class="form-group">
                <%= form.label :last_name , class:"mb-2"%>
                <%= form.text_field :last_name, class:"form-control form-control-lg rounded-0"%>
                </div>
                
                <% @employee.errors.full_messages_for(:last_name).each do |msg|%>
                <p class="text-danger"> <%= msg %> </p> 
                <%end%>
       </div>
       
       
      <div class="col-lg-4">
        <div class = "form-group">
           <%= form.label :middle_name, class:"mb-2"%>
           <%= form.text_field :middle_name, class:"form-control form-control-lg rounded-0"%> 
        </div>
      </div>
  </div>
  <div class="row">
                <div class= "col-lg-4 mt-4">
                                <div class="form-group">
                                <%= form.label :date_of_birth , class:"mb-2"%>
                                <%= form.date_field :date_of_birth, class:"form-control form-control-lg rounded-0"%>
                                </div>
                                
                                <% @employee.errors.full_messages_for(:date_of_birth).each do |msg|%>
                                <p class="text-danger"> <%= msg %> </p> 
                                <%end%>
                    </div>
                <div class= "col-lg-4 mt-4">
                                <div class="form-group">
                                <%= form.label :date_of_joining , class:"mb-2"%>
                                <%= form.date_field :date_of_joining, class:"form-control form-control-lg rounded-0"%>
                                </div>
                                
                                <% @employee.errors.full_messages_for(:date_of_joining).each do |msg|%>
                                <p class="text-danger"> <%= msg %> </p> 
                                <%end%>
                    </div>

                <div class= "col-lg-4 mt-4">
                                <div class="form-group">
                                <%= form.label :job_title , class:"mb-2"%>
                                <%= form.text_field :job_title, class:"form-control form-control-lg rounded-0"%>
                                </div>
                                
                                <% @employee.errors.full_messages_for(:job_title).each do |msg|%>
                                <p class="text-danger"> <%= msg %> </p> 
                                <%end%>
                    </div>
                <div class= "col-lg-12 mt-4">
                                <div class="form-group">
                                <%= form.label :about , class:"mb-2"%>
                                <%= form.text_area :about, class:"form-control form-control-lg rounded-0", rows:'5'%>
                                </div>
                                
                                <% @employee.errors.full_messages_for(:about).each do |msg|%>
                                <p class="text-danger"> <%= msg %> </p> 
                                <%end%>
                    </div>
  </div>

<div class= "row">
        <div class = "col-lg-6 mt-4"> 
            <div class="from-group">
                <%=form.label :email, class:'mb-2'%>
                <%= form.email_field :email, class:"form-control form-control-lg rounded-0"%>
            </div>
            <% @employee.errors.full_messages_for(:email).each do |msg|%>
             <p class= "text-danger"> <%= msg%> </p>
            <%end%>
        </div>

        <div class = "col-lg-6 mt-4"> 
            <div class="from-group">
                <%=form.label :address_line_1, class:'mb-2'%>
                <%= form.text_field :address_line_1, class:"form-control form-control-lg rounded-0"%>
            </div>
             <% @employee.errors.full_messages_for(:address_line_1).each do |msg|%>
             <p class ="text-danger"><%= msg%></p>
             <%end%>
        </div>
</div>

<div class= "row">
        

       <div class = "col-lg-3 mt-4">
            <div class="from-group">
                <%=form.label :city, class:'mb-2'%>
                <%= form.text_field :city, class:"form-control form-control-lg rounded-0"%>
            </div>
            <%@employee.errors.full_messages_for(:city).each do |msg|%>
             <p class= " text-danger"> <%=msg%> </p>
            <%end%>
        </div>
        <div class = "col-lg-3 mt-4">
            <div class="from-group">
                <%=form.label :state, class:'mb-2'%>
                <%= form.text_field :state, class:"form-control form-control-lg rounded-0"%>
                <%@employee.errors.full_messages_for(:state).each do |msg|%>
             <p class= " text-danger"> <%=msg%> </p>
            <%end%>
            </div>
        </div>
        <div class = "col-lg-3 mt-4">
            <div class="from-group">
                <%=form.label :country, class:'mb-2'%>
                <%= form.text_field :country, class:"form-control form-control-lg rounded-0"%>
            </div>
            <%@employee.errors.full_messages_for(:country).each do |msg|%>
             <p class= " text-danger"> <%=msg%> </p>
            <%end%>
        </div>

       <div class = "col-lg-3 mt-4"> 
            <div class="from-group">
                <%=form.label :pincode, class:'mb-2'%>
                <%= form.text_field :pincode, class:"form-control form-control-lg rounded-0"%>
            </div>
            <%@employee.errors.full_messages_for(:pincode).each do |msg|%>
             <p class= " text-danger"> <%=msg%> </p>
            <%end%>
        </div>
</div>

<div class="row">
   <div class= "col-lg-4 mt-3">
     <%= form.submit class: "btn btn-primary btn-lg mb-4 rounded-0"%>
     <%= link_to "Back To Employees" , employees_path,class: "btn btn-outline-primary btn-lg mb-4 rounded-0" %>
   </div>
</div>

<%end%>

app/views/employees/edit.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-4 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Edit Employee Information </h2>
        </div>
    </div>

  <%= render 'form', employee:@employee%>

</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
<%= flash[:notice]%>
    <div class="card rounded-0 mt-5 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Listing Employees </h2>
        </div>
    </div>
    <%= link_to "Create New Employee", new_employee_path, class: "btn btn-primary btn-lg mb-4 "%>
     <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Vies list In
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Table", employees_path(view_type:"table"), class: "dropdown-item "%></li>
                <li><%= link_to "accordian", employees_path(view_type:"accordian"), class: "dropdown-item "%></li>

            </ul>
   </div>
    
<% if params[:view_type] != 'accordian'%>
    
    
    <table class ="table table-bordered text-center ">
        <thead>
            <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Action</th>
            </tr>
    </thead>
        <tbody>
            <% @employees.each  do |employee|%>
                <tr>
                    <td><%= employee.name%></td>
                    <td><%= employee.email%></td>
                    <td><%= employee.address%></td>
                    <td>
            <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Edit", edit_employee_path(employee), class: "dropdown-item "%></li>
                <li><%= link_to "View", employee_path(employee), class: "dropdown-item"%></li>
                <li><%= link_to "Delete", employee_path(employee), class: "dropdown-item", method: :delete, data: {confirm: "Are You sure delete this employee?"}%></li>
            </ul>
            </div>
 <!--   Button(edit / view / delete) dene ka another way         
 <%= link_to "View", employee_path(employee), class: "btn btn-info btn-lg mb-4"%>

<%= link_to "Delete", employee_path(employee), class: "btn btn-danger btn-lg mb-4", method: :delete, data: {confirm: "Are You sure delete this employee?"}%>
<%= link_to "Edit", edit_employee_path(employee), class: "btn btn-primary btn-lg mb-4"%>
-->
            </td>

                </tr>
            <%end%>
        </tbody>
    </table>

<%end%>

<% if params[:view_type].present?  &&  params[:view_type] == 'accordian'%>

    <div class="accordion" id="accordionExample">
      <%@employees.each_with_index do |employee,index|%>
            <div class="accordion-item">
                        <h2 class="accordion-header" id="heading_<%=index + 1%>">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%=index + 1%>" aria-expanded="true" aria-controls="collapse_<%=index + 1%>">
                            <%=employee.name_with_email%>
                        </button>
                        </h2>
                        <div id="collapse_<%=index + 1%>" class="accordion-collapse collapse " aria-labelledby="heading_<%=index + 1%>" data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                        <h2 class="text-center">  Employee Details  </h2>
                    <div class ="row mt-5">
                            <div class="col-lg-6">
                                <h3 class="mb-3">Personal Information</h1>
                                <p class="lead"><strong>First Name: </strong><%=employee.first_name%></p>
                                <p class="lead"><strong>Middle Name: </strong><%= employee.middle_name.present? ? employee.middle_name : "NA"%></p>
                                <p class="lead"><strong>Last Name: </strong><%=employee.last_name%></p>
                                <p class="lead"><strong>Email Name: </strong><%=employee.email%></p>
                            </div>

                            <div class="col-lg-6">
                                <h3 class="mb-3">Address Information</h1>
                                <p class="lead"><strong>Address: </strong><%=employee.address_line_1%></p>

                                <p class="lead"><strong>City: </strong><%=employee.city%></p>
                                <p class="lead"><strong>State: </strong><%=employee.state%></p>
                                <p class="lead"><strong>Country: </strong><%=employee.country%></p>
                                <p class="lead"><strong>Pincode: </strong><%=employee.pincode%></p>

                            </div>
                    </div>
                        <div class="col-lg-12">
                            <%= link_to "Edit", edit_employee_path(employee), class: "btn btn-primary"%>
                            <%#= link_to "View", employee_path(employee), class: "btn btn-primary"%>
                            <%= link_to "Delete", employee_path(employee), class: "btn btn-danger", method: :delete, data: {confirm: "Are You sure delete this employee?"}%>
                        </div>
                </div>
                </div>
            </div>
       <%end%>    
    </div>
<%end%>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
    <div class="card rounded-0 mt-4 mb-5">
        <div class="card-body">
            <h2 class="text-center"> Create New Employee </h2>
        </div>
    </div>
    <%= render 'form', employee:@employee%>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
<div class="card rounded-0 mt-4 mb-5">
    <div class="card-body">
        <h2 class="text-center">  Employee Details  </h2>
            <div class ="row mt-5">
                <div class="col-lg-6">
                    <h3 class="mb-3">Personal Information</h1>
                    <p class="lead"><strong>First Name: </strong><%=@employee.first_name%></p>
                    <p class="lead"><strong>Middle Name: </strong><%= @employee.middle_name.present? ? @employee.middle_name : "NA"%></p>
                    <p class="lead"><strong>Last Name: </strong><%=@employee.last_name%></p>
                    <p class="lead"><strong>Email Name: </strong><%=@employee.email%></p>
                </div>

                <div class="col-lg-6">
                    <h3 class="mb-3">Address Information</h1>
                    <p class="lead"><strong>Address: </strong><%=@employee.address_line_1%></p>

                    <p class="lead"><strong>City: </strong><%=@employee.city%></p>
                    <p class="lead"><strong>State: </strong><%=@employee.state%></p>
                    <p class="lead"><strong>Country: </strong><%=@employee.country%></p>
                    <p class="lead"><strong>Pincode: </strong><%=@employee.pincode%></p>
                    

                </div>
            </div>
            <div class="col-lg-6">
                    <h3 class="mb-3">Employee Information</h1>
                    <p class="lead"><strong>DOB: </strong><%=@employee.date_of_birth%></p>
                    <p class="lead"><strong>Job Title: </strong><%=@employee.job_title%></p>

                    <p class="lead"><strong>Joining Date: </strong><%=@employee.date_of_joining%></p>
                    <p class="lead"><strong>About: </strong><%=@employee.about%></p>
                   
                    

                </div>
            </div>


   <% if @employee.documents.present?%>
            <div class ="row mt-5">
             <h2 class="text-center">  Employee Documents  </h2>
             <% @employee.documents.each do |document|%>
                <div class="card mb-4">
                    <div class="card-body ">
                        <div class="row ">

                            <% if document.image.attached?%>
                                <div class="col-lg-4">
                                <%= image_tag document.image , class:"img-fluid"%>
                                </div>
                            <%end%>
                        
                            <div class="col-lg-4">
                               <p class="lead"><%= document.name%></p>
                            </div>

                            <div class="col-lg-4">
                                <p class="lead"><%= document.doc_type%></p>
                            </div>
                    </div>
                </div>
             <%end%>
            </div>

    <%end%>   
     <%= link_to "Edit Employee", edit_employee_path(@employee), class:"btn btn-primary btn-lg"%>
     <%= link_to "Back to Employees", employees_path, class:"btn btn-outline-primary btn-lg "%>

    </div>
</div>

</div>

app/views/home/index.html.erb
<h1><%= @title%></h1>
<p><%= @sub_title%></p>

<!--
<%= link_to 'About us', about_path, target: "_blank", data: {name:'abouts page',resources:'pages'}%>

<%= link_to 'contact us', controller: :pages, action: :contact_us%>
<%= link_to 'contact us', controller: 'pages', action: 'contact_us'%>

<%= link_to 'About us' ,'/about'%>
<%= link_to nil , about_path%>
-->
<%= render 'shared/links'%>

app/views/pages/about_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">About HR-Mitra</h1>
  <%= render "shared/dummy_content"%>
</div>


<%= render 'shared/links'%>

app/views/pages/contact_us.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Contact Us</h1>
  <%= render "shared/dummy_content"%>
</div>

<%= render 'shared/links'%>

app/views/pages/privacy_policy.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Privacy Policy</h1>
  <%= render "shared/dummy_content"%>
</div>
<%= render 'shared/links'%>

app/views/pages/terms_and_conditions.html.erb
<div class="col-lg-10 mx-auto">
  <h1 class="text-center mt-5 mb-4">Terms & Conditions</h1>
  <%= render "shared/dummy_content"%>
</div>

<%= render 'shared/links'%>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom mb-10">
    <!-- Left -->
    <div class="mb-20 d-none d-lg-block">
      <span><h1>Hr-Mitra</h1></span>
    </div>
  </section>

  
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <%= link_to 'About us', about_path, target: "_blank", style: 'color:red'%>
      <%= link_to 'Contact us',contact_path, target: "_blank"%>
      <%= link_to 'Privacy Policy', privacy_policy_path, target: "_blank"%>
      <%= link_to 'Terms and Conditions', terms_and_conditions_path, target: "_blank"%>
     </div>
 </section>   

    
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_links.html.erb
<h1>HR Mitra </h1>
<%= link_to 'About us', about_path, target: "_blank", style: 'color:red'%>
<%= link_to 'Contact us',contact_path, target: "_blank"%>
<%= link_to 'Privacy Policy', privacy_policy_path, target: "_blank"%>
<%= link_to 'Terms and Conditions', terms_and_conditions_path, target: "_blank"%>